{% set name = "forallpeople" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/forallpeople-{{ version }}.tar.gz
  sha256: 6e5e3c5d6244db3ff5d4bf84717b7d48c31a8705fc05edfa3c74a57222eb482b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - flit-core >=2,<4
    - pip
  run:
    - python >=3.8

test:
  imports:
    - forallpeople
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://connorferster.github.io/forallpeople
  summary: 'The SI Units: "For all people, for all time"'
  dev_url: https://github.com/connorferster/forallpeople
  license: Apache-2.0
  license_file: LICENSE.TXT

extra:
  recipe-maintainers:
    - connorferster
